name: PR workflow

on: push

jobs:
  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.0'
      - run: npm install
      - run: npm run lint-dockerfile