name: PR workflow

on: push

jobs:
  lint-dockerfile-yaml:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.0"
      - run: npm install --also=dev
      - run: npm run lint-dockerfile
      - run: npm run lint-yaml

  test:
    name: Unit and Functional Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.0"
      - run: npm install --also=dev
      - run: npm run test
